apiVersion: v1 
kind: Pod 
metadata: 
    name: dind 
spec: 
    containers: 
      - name: docker-cmds 
        image: docker:1.12.6 
        command: ['docker', 'run', '-p', '80:80', 'httpd:latest'] 
        resources: 
            requests: 
                cpu: 10m 
                memory: 256Mi 
        env: 
          - name: DOCKER_HOST 
            value: tcp://localhost:2375 
      - name: dind-daemon 
        image: docker:18.09.6-dind 
        command: ['dockerd', '-H', '0.0.0.0:2375']
        resources: 
            requests: 
                cpu: 20m 
                memory: 512Mi 
        securityContext: 
            privileged: true 
        env:
          - name: CONTAINERD_NAMESPACE
            value: k8s.io
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker/containers
    volumes: 
      - name: docker-graph-storage 
        hostPath:
          path: /var/lib/docker/io.containerd.grpc.v1.cri/containers
          type: Directory
