apiVersion: "kapitan.razee.io/v1alpha1"
kind: MustacheTemplate
metadata:
  name: feature-flag-template
  namespace: default
spec:
  env:
  # Feature flags
  - name: istio
    value: false
  - name: knative
    value: false
  - name: goldpinger
    value: false
  - name: dind
    value: false
  - name: nginx
    value: false
  # Versions for flagged features above
  - name: istio-version
    value: "1.1.7"
  - name: knative-version
    value: "0.6.0"
  - name: goldpinger-version
    value: "1.5.0"
  - name: dind-version
    value: "18.09.6"
  - name: nginx
    value: "1.7.9"
  templates:
  - apiVersion: "kapitan.razee.io/v1alpha1"
    kind: RemoteResource
    metadata:
      name: feature-flags
      namespace: default
    spec:
      requests:
      {{#istio}}
      - options:
          url: https://raw.githubusercontent.com/jpapejr/razee-samples/master/istio-v{{istio-version}}.yaml
      {{/istio}}
      {{#knative}}
      - options:
          url: https://raw.githubusercontent.com/jpapejr/razee-samples/master/knative-v{{knative-version}}.yaml
      {{/knative}}
      {{#goldpinger}}
      - options:
          url: https://raw.githubusercontent.com/jpapejr/razee-samples/master/goldpinger-v{{goldpinger-version}}.yaml
      {{/goldpinger}}
      {{#dind}}
      - options:
          url: https://raw.githubusercontent.com/jpapejr/razee-samples/master/dind-v{{dind-version}}.yaml
      {{/dind}}
      {{#nginx}}
      - options:
          url: https://raw.githubusercontent.com/jpapejr/razee-samples/master/nginx-v{{nginx-version}}.yaml
      {{/nginx}}
