kind: ManagedSet
apiVersion: kapitan.razee.io/v1alpha1
metadata:
  name: features
  namespace: default
spec:
  resources:
    - apiVersion: "kapitan.razee.io/v1alpha1"
      kind: RemoteResource
      metadata:
        name: autorecovery-feature
        namespace: default
      spec:
        requests:
        - options:
            url: https://raw.githubusercontent.com/jpapejr/razee-samples/master/autorecovery-v1.10.46.yaml
    - apiVersion: "kapitan.razee.io/v1alpha1"
      kind: RemoteResource
      metadata:
        name: istio-1.2.2-feature
        namespace: default
      spec:
        requests:
        - options:
            url: https://raw.githubusercontent.com/jpapejr/razee-samples/master/istio-v1.2.2.yaml
